# Numerical Python(Numpy) - Part 1

In [1]:
# de facto standard(사실상의 표준)
import numpy as np

In [2]:
a = [1,2,3]
a * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [7]:
# 이런 수고 필요없이
list(map(lambda x: 3*x, a))

[3, 6, 9]

In [8]:
# 이렇게 가능
b = np.array([1,2,3])
b * 3

array([3, 6, 9])

## 1. Numpy Dimensional Array

In [10]:
 a = np.array([1,4,5,8], float)
 a

array([1., 4., 5., 8.])

In [11]:
type(a)

numpy.ndarray

In [12]:
a.dtype, a.shape

(dtype('float64'), (4,))

In [13]:
# 하나의 데이터 타입만 배열에 넣을 수 있음

## 2. Array shape

In [16]:
# Vector(1차원)
vec = np.array([1,4,5,8])
vec.shape

(4,)

In [18]:
# Matrix(2차원)
matrix = np.array([[1,2,3], [4,5,6]])
print(matrix.shape)
matrix

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Tensor(3차원 이상)
# 입력이 어려워서 이렇게 입력함 (원래 이렇게 쓰는게 정석)
tensor = np.arange(1,25).reshape(2,3,4)
print(tensor)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [20]:
tensor.shape

(2, 3, 4)

In [21]:
vec.shape, matrix.shape, tensor.shape

((4,), (2, 3), (2, 3, 4))

In [22]:
# 원소(element) 갯수
vec.size, matrix.size, tensor.size

(4, 6, 24)

In [23]:
a = np.array([1,2,3], dtype = np.float32)
# a = np.array([1,2,3], np.float32)
a

array([1., 2., 3.], dtype=float32)

In [26]:
b = np.array([1,2,3], dtype = np.int16)
b

array([1, 2, 3], dtype=int16)

 ## reshape

In [27]:
# array의 shape 변경(element 개수는 동일)
matrix.shape

(2, 3)

In [29]:
matrix.reshape(6,)

array([1, 2, 3, 4, 5, 6])

In [30]:
matrix.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [31]:
# 알아서 맞춰줌
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [32]:
matrix.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [33]:
matrix.reshape(3, -1).shape

(3, 2)

In [36]:
tensor.reshape(4, -1)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [37]:
tensor.reshape(4, -1).shape

(4, 6)

In [38]:
matrix.reshape(-1,)

array([1, 2, 3, 4, 5, 6])

In [39]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [40]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [43]:
matrix.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## flatten

In [47]:
tensor.reshape(-1,)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [46]:
tensor.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## 3. Indexing & Slicing

### Indexing

In [49]:
matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
matrix[0][1]

2

In [51]:
matrix[0,1]

2

In [52]:
tensor[1,1,2]

19

### slicing

In [53]:
b = np.arange(16).reshape(4,-1)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
# 5,6,9,10
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [57]:
# 5,6,7,9,10,11
b[1:3, 1:]

array([[ 5,  6,  7],
       [ 9, 10, 11]])

In [59]:
# 1,3,9,11
b[::2, 1::2]

array([[ 1,  3],
       [ 9, 11]])

In [61]:
# X는 앞에 3열(마지막열 제외한 전체 열), y는 마지막 열
X, y = b[:, :-1], b[:, -1]
X.shape, y.shape

((4, 3), (4,))