# 연습문제

In [2]:
import numpy as np

### 1. 행렬 만들기

In [3]:
np.arange(1,9).reshape(2,4) * 10

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

### 2. 인덱싱, 슬라이싱

In [4]:
m = np.arange(15).reshape(3,5)

In [5]:
# 2-1, 2-2
m[1,2], m[-1,-1]

(7, 14)

In [6]:
# 2-3
m[1, 1:3]

array([6, 7])

In [7]:
# 2-4
m[1:, 2]

array([ 7, 12])

In [8]:
# 2-5
m[:2, 3:]

array([[3, 4],
       [8, 9]])

### Boolean Indexing

In [9]:
f = m.flatten()

In [10]:
# 3-1
f[f % 3 == 0]

array([ 0,  3,  6,  9, 12])

In [11]:
# 3-2
f[f % 4 == 1]

array([ 1,  5,  9, 13])

In [12]:
# 3-3
f[np.logical_and(f%3==0, f%4==1)]

array([9])

### 4. eye로 행렬 만들기

In [13]:
np.eye(5,5,k=-1)*3 + np.eye(5,5)*2 + np.eye(5,5,k=1)

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### 5. Matrix operation

In [14]:
np.random.seed(2021)
m = np.random.uniform(0,10,30).reshape(5,6).round(4)
m

array([[6.0598, 7.3337, 1.3895, 3.1267, 9.9724, 1.2816],
       [1.7899, 7.5293, 6.6216, 7.8431, 0.9689, 0.5857],
       [9.624 , 6.1656, 0.8663, 5.6127, 6.1652, 9.6384],
       [5.743 , 3.7116, 4.5215, 2.0185, 5.6931, 1.951 ],
       [5.837 , 4.7631, 5.1781, 8.231 , 7.3223, 0.6906]])

In [15]:
# 5-1
np.max(m)

9.9724

In [16]:
# 5-2
np.sum(m, axis=1)

array([29.1637, 25.3385, 38.0722, 23.6387, 32.0221])

In [17]:
# 5-3
np.max(m, axis=1)

array([9.9724, 7.8431, 9.6384, 5.743 , 8.231 ])

In [18]:
# 5-4
np.mean(m, axis=0)

array([5.81074, 5.90066, 3.7154 , 5.3664 , 6.02438, 2.82946])

In [19]:
# 5-5
np.min(m, axis=0)

array([1.7899, 3.7116, 0.8663, 2.0185, 0.9689, 0.5857])

### 6. Sorting

In [20]:
score = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [21]:
np.sort(score)

array([[  1,   2,   3,   4],
       [ 46,  71,  99, 100],
       [ 59,  81,  90, 100]])

In [22]:
s = np.argsort(score[1])
s

array([0, 3, 1, 2])

In [23]:
# 내림차순
s[::-1]

array([2, 1, 3, 0])

In [24]:
score[:, s[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [25]:
# 한 줄로
score[:, np.argsort(score[1])[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

### 7. 주사위 100번

In [26]:
np.random.seed(2021)
dice = np.random.randint(1,7,100)
dice

array([5, 6, 2, 1, 6, 5, 4, 6, 6, 6, 1, 5, 2, 6, 2, 2, 5, 6, 3, 3, 1, 4,
       2, 1, 3, 4, 5, 6, 1, 6, 2, 3, 6, 2, 6, 2, 3, 3, 5, 6, 3, 4, 2, 3,
       3, 1, 3, 5, 6, 4, 4, 2, 2, 2, 3, 6, 4, 4, 5, 4, 2, 5, 2, 2, 5, 4,
       6, 4, 4, 4, 3, 2, 4, 3, 6, 3, 3, 1, 5, 4, 2, 4, 2, 5, 3, 4, 2, 3,
       6, 3, 6, 3, 4, 5, 6, 2, 2, 6, 1, 6])

In [27]:
np.mean(dice)

3.7